//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace WindowsClient.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmployeesServiceSoap", Namespace="http://www.apress.com/ProASP.NET/")]
    public class EmployeesServiceWse : Microsoft.Web.Services2.WebServicesClientProtocol {
        
        /// <remarks/>
        public EmployeesServiceWse() {
            this.Url = "http://localhost/Chapter26_WSE/EmployeesService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/GetEmployees", RequestNamespace="http://www.apress.com/ProASP.NET/", ResponseNamespace="http://www.apress.com/ProASP.NET/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEmployees() {
            object[] results = this.Invoke("GetEmployees", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetEmployees(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetEmployees", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetEmployees(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmployeesServiceSoap", Namespace="http://www.apress.com/ProASP.NET/")]
    public class EmployeesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public EmployeesService() {
            this.Url = "http://localhost/Chapter26_WSE/EmployeesService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/GetEmployees", RequestNamespace="http://www.apress.com/ProASP.NET/", ResponseNamespace="http://www.apress.com/ProASP.NET/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEmployees() {
            object[] results = this.Invoke("GetEmployees", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetEmployees(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetEmployees", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetEmployees(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
