//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace WindowsClient.StatefulWebService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StatefulServiceSoap", Namespace="http://tempuri.org/")]
    public class StatefulService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public StatefulService() {
            this.Url = "http://localhost/Chapter24/StatefulService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StoreName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StoreName(string name) {
            this.Invoke("StoreName", new object[] {
                        name});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStoreName(string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StoreName", new object[] {
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndStoreName(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetName() {
            object[] results = this.Invoke("GetName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetName(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetName", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
