//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Chapter26.localhost2 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoapSecurityServiceSoap", Namespace="http://tempuri.org/")]
    public class SoapSecurityService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public TicketHeader TicketHeaderValue;
        
        /// <remarks/>
        public SoapSecurityService() {
            this.Url = "http://localhost/Chapter26/SoapSecurityService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TicketHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Login(string userName, string password, HashAlgorithm hashAlgorithm) {
            this.Invoke("Login", new object[] {
                        userName,
                        password,
                        hashAlgorithm});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogin(string userName, string password, HashAlgorithm hashAlgorithm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Login", new object[] {
                        userName,
                        password,
                        hashAlgorithm}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndLogin(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TicketHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmployees", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEmployees() {
            object[] results = this.Invoke("GetEmployees", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetEmployees(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetEmployees", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetEmployees(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public class TicketHeader : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string Ticket;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum HashAlgorithm {
        
        /// <remarks/>
        SHA1,
        
        /// <remarks/>
        MD5,
        
        /// <remarks/>
        Clear,
    }
}
